= MicroProfile LRA 2.0 Compatible Certification Request

== Specification details

Repository - https://github.com/eclipse/microprofile-lra

=== MicroProfile LRA 2.0

Tag - https://github.com/eclipse/microprofile-lra/releases/tag/2.0


 Commit - https://github.com/eclipse/microprofile-lra/commit/f48f1a64db92940e64737b8ba703bff7d36034f2

Download - https://download.eclipse.org/microprofile/staging/microprofile-lra-2.0

=== MicroProfile LRA 2.0-RC1 (used for the CCR)

Tag - https://github.com/eclipse/microprofile-lra/releases/tag/2.0-RC1

Commit - https://github.com/eclipse/microprofile-lra/commit/bc66393c44dada2ac63f2144038d4ecca449b21e

Download - https://download.eclipse.org/microprofile/microprofile-lra-2.0-RC1


There are no differences between LRA 2.0 and LRA 2.0-RC1. The API and TCK binaries are the same.

== Implementation details

Implementation Name - [Narayana LRA](https://narayana.io/)

 Version - 0.0.9.Final

Download Source Code - https://github.com/jbosstm/lra/tree/0.0.9.Final

VCS revision tag - https://github.com/jbosstm/lra/releases/tag/0.0.9.Final

VCS revision commit - https://github.com/jbosstm/lra/commit/eaca2e0ce9f7f9d904d53956228382751fb48352

== Compatibility Certification Request JDK 17

=== Environment details

Output of `uname -a`:

[source,bash]
----
Linux XYZ 6.11.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 22 19:13:11 UTC 2024 x86_64 GNU/Linux
----

Output of `java -version`

[source,bash]
----
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment (Red_Hat-17.0.13.0.11-1) (build 17.0.13+11)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.13.0.11-1) (build 17.0.13+11, mixed mode, sharing)
----

and (JDK21)

[source,bash]
----
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11, mixed mode, sharing)
----

Output of `mvn -version`

[source,bash]
----
Apache Maven 3.9.6 (Red Hat 3.9.6-6)
Maven home: /usr/share/maven
Java version: 17.0.13, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.13.0.11-1.fc40.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.11.5-200.fc40.x86_64", arch: "amd64", family: "unix"
----

=== CCR execution JDK 17 and JDK 21

Command - `WORKSPACE=$PWD PROFILE=LRA ./scripts/hudson/narayana.sh`

Results failsafe-reports zips - xref:lra-2.0-jdk-17-ccr-results.zip[lra-2.0-jdk-17-ccr-results.zip] and xref:lra-2.0-jdk-21-ccr-results.zip[lra-2.0-jdk-21-ccr-results.zip]

Results:

[source,bash]
----
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckCancelOnTests
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.782 s - in org.eclipse.microprofile.lra.tck.TckCancelOnTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckContextTests
-------------------------------------------------------------------------------
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.704 s - in org.eclipse.microprofile.lra.tck.TckContextTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckInvalidSignaturesTests
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.222 s - in org.eclipse.microprofile.lra.tck.TckInvalidSignaturesTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckLRATypeTests
-------------------------------------------------------------------------------
Tests run: 75, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.07 s - in org.eclipse.microprofile.lra.tck.TckLRATypeTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckParticipantTests
-------------------------------------------------------------------------------
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.567 s - in org.eclipse.microprofile.lra.tck.TckParticipantTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckRecoveryTests
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.805 s - in org.eclipse.microprofile.lra.tck.TckRecoveryTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckTests
-------------------------------------------------------------------------------
Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.766 s - in org.eclipse.microprofile.lra.tck.TckTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckUnknownStatusTests
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.166 s - in org.eclipse.microprofile.lra.tck.TckUnknownStatusTests
-------------------------------------------------------------------------------
Test set: org.eclipse.microprofile.lra.tck.TckUnknownTests
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 42.176 s - in org.eclipse.microprofile.lra.tck.TckUnknownTests

[INFO] Results:
[INFO]
[INFO] Tests run: 133, Failures: 0, Errors: 0, Skipped: 0
----

== Replicating the TCK execution

[source,bash]
----
git clone https://github.com/jbosstm/lra.git -b 0.0.9.Final && cd lra

WORKSPACE=$PWD PROFILE=LRA ./scripts/hudson/narayana.sh
----

